-- MySQL Script generated by MySQL Workbench
-- Tue Mar 10 22:47:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Backup_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Backup_details` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Backup_details` (
  `date` DATE NOT NULL,
  `path` VARCHAR(255) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`address_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`address_info` (
  `address_id` INT NOT NULL,
  `city` VARCHAR(50) NULL,
  `lane1` VARCHAR(50) NULL,
  `lane2` VARCHAR(50) NULL,
  `pincode` INT NULL,
  `state` VARCHAR(50) NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`common_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`common_master` ;

CREATE TABLE IF NOT EXISTS `mydb`.`common_master` (
  `title` VARCHAR(255) NOT NULL,
  `record` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`contact_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contact_person` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contact_person` (
  `customer_id` INT NOT NULL,
  `contact_person_id` INT NOT NULL AUTO_INCREMENT,
  `contact_person_name` VARCHAR(45) NOT NULL,
  `contact_person_designation` VARCHAR(45) NOT NULL,
  `contact_person_number` BIGINT(12) NOT NULL,
  `contact_person_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`contact_person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customer_master` ;

CREATE TABLE IF NOT EXISTS `mydb`.`customer_master` (
  `customer_name` VARCHAR(50) NOT NULL,
  `customer_address_id` INT NOT NULL,
  `customer_phone_number` BIGINT(12) NOT NULL,
  `customer_email_id` VARCHAR(255) NOT NULL,
  `customer_reg_date` DATETIME NOT NULL,
  `customer_id` INT NOT NULL,
  `customer_discount_id` INT NOT NULL,
  `customer_registration_employee_id` INT NOT NULL,
  `contact_person_customer_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`discount_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`discount_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`discount_info` (
  `discount_id` INT NOT NULL,
  `discount_percentage` FLOAT NOT NULL,
  `remark` VARCHAR(255) NOT NULL,
  `customer_master_customer_id` INT NOT NULL,
  PRIMARY KEY (`discount_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`element_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`element_master` ;

CREATE TABLE IF NOT EXISTS `mydb`.`element_master` (
  `element type` VARCHAR(255) NOT NULL,
  `element name` VARCHAR(255) NOT NULL,
  `isferrous` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`employee_registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employee_registration` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employee_registration` (
  `employee_name` VARCHAR(50) NOT NULL,
  `employee_address_id` INT NOT NULL,
  `employee_mobile_no` BIGINT(12) NOT NULL,
  `employee_email_id` VARCHAR(255) NOT NULL,
  `employee_reg_date` DATETIME NOT NULL,
  `employee_id` INT NOT NULL,
  `employee_status` ENUM('') NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`invoice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`invoice` (
  `invoice_no` VARCHAR(255) NOT NULL,
  `invoice_date` DATETIME NOT NULL,
  `mrn(po/dc)` VARCHAR(255) NOT NULL,
  `customer_id` VARCHAR(45) NOT NULL,
  `net amount` FLOAT NOT NULL,
  `status` ENUM('PAID', 'UNPAID') NOT NULL,
  `challan_no` VARCHAR(45) NOT NULL,
  `challan_date` DATETIME NOT NULL,
  `net_amount` FLOAT NOT NULL,
  `credit_days` DATETIME NULL,
  `w_o_no` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`invoice_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`invoice_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`invoice_report` ;

CREATE TABLE IF NOT EXISTS `mydb`.`invoice_report` (
  `invoice no` VARCHAR(255) NOT NULL,
  `customer name` VARCHAR(255) NOT NULL,
  `w.o.no` VARCHAR(255) NOT NULL,
  `invoice date` DATETIME NOT NULL,
  `po.no` VARCHAR(255) NOT NULL,
  `total amount` FLOAT NOT NULL,
  `net amount` FLOAT NOT NULL,
  `invoice_invoice_no` VARCHAR(255) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`lab_analysis_entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lab_analysis_entry` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lab_analysis_entry` (
  `test` VARCHAR(255) NOT NULL,
  `work order no` VARCHAR(255) NOT NULL,
  `customer name` VARCHAR(255) NOT NULL,
  `sample no` VARCHAR(255) NOT NULL,
  `material description` VARCHAR(255) NOT NULL,
  `method name` VARCHAR(255) NOT NULL,
  `specification name` VARCHAR(255) NOT NULL,
  `sub test` VARCHAR(255) NOT NULL,
  `main test` VARCHAR(255) NOT NULL,
  `delivery date` DATE NOT NULL,
  `status` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`login_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`login_data` ;

CREATE TABLE IF NOT EXISTS `mydb`.`login_data` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NOT NULL,
  `role_id` INT NOT NULL,
  `last_login` DATETIME NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `role_permissions_role_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`main_test_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`main_test_master` ;

CREATE TABLE IF NOT EXISTS `mydb`.`main_test_master` (
  `department name` VARCHAR(255) NOT NULL,
  `main test name` VARCHAR(255) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`material_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`material_master` ;

CREATE TABLE IF NOT EXISTS `mydb`.`material_master` (
  `material name` VARCHAR(255) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`observation_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`observation_master` ;

CREATE TABLE IF NOT EXISTS `mydb`.`observation_master` (
  `test form` VARCHAR(255) NOT NULL,
  `observation` VARCHAR(255) NOT NULL,
  `sub_test_master_subtest_id` INT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`payment_received_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payment_received_report` ;

CREATE TABLE IF NOT EXISTS `mydb`.`payment_received_report` (
  `payment transaction no` VARCHAR(255) NOT NULL,
  `invoice_no` VARCHAR(255) NOT NULL,
  `customer name` VARCHAR(255) NOT NULL,
  `bill regenrate` VARCHAR(255) NOT NULL,
  `voucher no` VARCHAR(255) NOT NULL,
  `transation date` DATETIME NOT NULL,
  `payment mode` VARCHAR(500) NOT NULL,
  `cheque no` VARCHAR(255) NOT NULL,
  `cheque date` DATE NOT NULL,
  `payment description` TEXT NOT NULL,
  `amount` FLOAT NOT NULL,
  `deduct amount description` TEXT NOT NULL,
  `employee_id` VARCHAR(45) NULL,
  `invoice_invoice_no` VARCHAR(255) NOT NULL,
  `transaction_report_transaction_id` VARCHAR(45) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`product_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_master` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_master` (
  `name` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `re-order quantity` INT(5) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`rate_card_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rate_card_master` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rate_card_master` (
  `sun test name` VARCHAR(255) NOT NULL,
  `test description` TEXT NOT NULL,
  `price` FLOAT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`registration_entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registration_entry` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registration_entry` (
  `sample_no` INT(11) NOT NULL COMMENT 'views creation ',
  `sample_reg_no` INT(11) NOT NULL,
  `coustomer_name` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `delivery_date` INT(11) NOT NULL,
  `challan_no` INT(11) NOT NULL,
  `challan_date` DATE NOT NULL,
  `no_of_sample` INT(11) NOT NULL,
  `name_analysis_print` INT(11) NOT NULL,
  `remark` INT(11) NOT NULL,
  `work_order_print` INT(11) NOT NULL,
  `upload_doc` GEOMETRYCOLLECTION NOT NULL,
  PRIMARY KEY (`sample_no`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`renewal_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`renewal_master` ;

CREATE TABLE IF NOT EXISTS `mydb`.`renewal_master` (
  `product` VARCHAR(255) NOT NULL,
  `starting date` DATE NOT NULL,
  `notification type` VARCHAR(255) NOT NULL,
  `notification duration` VARCHAR(255) NOT NULL,
  `status` TEXT NOT NULL,
  `remarks` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`role_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`role_permissions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`role_permissions` (
  `role_id` INT NOT NULL,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sample_registration_entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sample_registration_entry` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sample_registration_entry` (
  `sample_no` VARCHAR(45) NOT NULL,
  `sample_reg_no` VARCHAR(45) NOT NULL,
  `customer_id` VARCHAR(45) NOT NULL,
  `collection_date` DATETIME NOT NULL,
  `delivery_date` DATETIME NOT NULL,
  `d challon no` VARCHAR(255) NOT NULL,
  `challon_date` DATETIME NOT NULL,
  `no_of_sample` INT NULL,
  `name_of_analysis_print` INT(5) NOT NULL,
  `remarks` TEXT NOT NULL,
  `employee_id` VARCHAR(45) NULL,
  `employee_registration_employee_id` VARCHAR(45) NOT NULL,
  `invoice_invoice_no` VARCHAR(255) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`serial_no_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`serial_no_master` ;

CREATE TABLE IF NOT EXISTS `mydb`.`serial_no_master` (
  `form name` VARCHAR(255) NOT NULL,
  `serial no` INT(10) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`specification_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`specification_master` ;

CREATE TABLE IF NOT EXISTS `mydb`.`specification_master` (
  `specification name` VARCHAR(255) NOT NULL,
  `material grade` VARCHAR(255) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`sub_test_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sub_test_master` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sub_test_master` (
  `subtest_id` INT NOT NULL AUTO_INCREMENT,
  `subtest_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`subtest_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`supplier` ;

CREATE TABLE IF NOT EXISTS `mydb`.`supplier` (
  `supplier id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `email_id` VARCHAR(255) NOT NULL,
  `contact no` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`supplier id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`test_method_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`test_method_master` ;

CREATE TABLE IF NOT EXISTS `mydb`.`test_method_master` (
  `sub_test_id` INT NOT NULL,
  `test method` VARCHAR(255) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`test_standard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`test_standard` ;

CREATE TABLE IF NOT EXISTS `mydb`.`test_standard` (
  `sub_test_id` INT NOT NULL,
  `test_id` INT NOT NULL,
  `standard_result` VARCHAR(255) NOT NULL,
  `std_result_date` INT NOT NULL,
  `sub_test_master_subtest_id` INT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`transaction_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transaction_report` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transaction_report` (
  `transaction type` VARCHAR(255) NOT NULL,
  `payment type` VARCHAR(255) NOT NULL,
  `payment description` VARCHAR(255) NOT NULL,
  `credit amount` FLOAT NOT NULL,
  `debit amoount` FLOAT NOT NULL,
  `transaction date` DATE NOT NULL,
  `transaction_id` VARCHAR(45) NOT NULL,
  `invoice_no` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`transaction_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vendor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vendor` (
  `transaction type` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `email_id` VARCHAR(255) NOT NULL,
  `contact no` VARCHAR(15) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`working_notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`working_notification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`working_notification` (
  `working_notification_id` VARCHAR(45) NOT NULL,
  `employee_id` VARCHAR(45) NOT NULL,
  `notification_date` DATETIME NOT NULL,
  `notes` TEXT NOT NULL,
  `remarks` TEXT NOT NULL,
  `sample_no` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `sample_no_UNIQUE` (`sample_no` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;
 

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
